[project]
name = "image-viewer-pro"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.119.1",
    "numpy>=2.3.4",
    "opencv-python>=4.11.0.86",
    "pillow>=12.0.0",
    "uvicorn>=0.38.0",
]
